name: Panama Canal Adventures
favicon: null
layout_spectrum: 0.25294
typography_spectrum: 0.83017
title: Welcome to the Panama Canal
description: Find all the Panama Canal activities available here!
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#223671'
    - '#319bcb'
    - '#b3deee'
    - '#bdb93d'
    - '#839910'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
