name: Panama Canal Adventures
favicon: null
layout_spectrum: 0.6510688401758671
typography_spectrum: 0.843113215174526
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.43674824154004455
  lightness: 0.6011576161254197
  saturation: 0.8639008565805852
  rhythmicContrast: 0.13095587119460106
purpose: []
