typography_spectrum: 0.65583
color:
  brandColors:
    - '#223671'
    - '#319bcb'
    - '#b3deee'
    - '#bdb93d'
    - '#839910'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2421
analytics:
  google: null
  facebook: null
  twitter: null
name: Panama Canal Adventures
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: History
    id: ed38958c-2dc9-4681-82a8-292439ee7c92
    type: content
  - name: About
    id: fb097c42-71ce-4785-a615-743cf7860262
    type: content
favicon: null
title: Welcome to the Panama Canal
description: Find all the Panama Canal activities available here!
purpose: []
